# Generated by Django 5.1.5 on 2025-01-26 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=255, verbose_name='Room name')),
            ],
            options={
                'verbose_name': 'Rooms',
                'verbose_name_plural': 'Room',
            },
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=255, verbose_name='Sender name')),
                ('message', models.TextField(verbose_name='Message content')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat_app.room', verbose_name='Room name')),
            ],
            options={
                'verbose_name': 'Messages',
                'verbose_name_plural': 'Message',
            },
        ),
    ]
